"""Updating market history table

Revision ID: 57627d964ca9
Revises: 
Create Date: 2025-07-13 12:17:16.845149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57627d964ca9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_history', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_market_history_type_id'), 'market_history', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_history_type_id'), table_name='market_history')
    op.drop_column('market_history', 'type_id')
    # ### end Alembic commands ###
