name: Deploy to Server

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H 192.168.178.50 >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 192.168.178.50
        username: gissa
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /eve-trading-dashboard
          git pull origin main
          docker compose down
          docker compose up -d --build